### PR TITLE
[FEATURE] Add Screenshot of plugin with advanced flexform

### PR DESCRIPTION
**Pull request by linawolf**

### CODE REVIEW

**Review by alexander-nitsche — CHANGES_REQUESTED** [review]
1) Disable extensions `EXT:introduction` and `EXT:styleguide` in the Extension Manager and remove the according DB tables and fields before exporting to not add 3rd-party extension fields to EXT:examples data dump.
2) Exclude files from data dump `data.xml`. There is an option in the Export tool in the third tab for it.

**Comment by linawolf** [comment]
Please have another look @alexander-nitsche

**Review by alexander-nitsche — CHANGES_REQUESTED** [review]
I do not see any changes.

**Review by alexander-nitsche — CHANGES_REQUESTED** [review]
The `EXT:bootstrap_package` needs to be uninstalled and DB compared too. It comes bundled with `EXT:introduction`. Search for e.g. "bootstrap" in data.xml.

**Review by alexander-nitsche — APPROVED** [review]

**Pull request merged**
